# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/interfaz_registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 667)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 661))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\\../../../Desktop/Diseño sin título.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.TextoIES = QtWidgets.QLabel(Form)
        self.TextoIES.setGeometry(QtCore.QRect(140, 110, 361, 111))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TextoIES.setFont(font)
        self.TextoIES.setStyleSheet("background-color: transparent;")
        self.TextoIES.setObjectName("TextoIES")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(790, 0, 161, 181))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("ui\\../../../Desktop/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(660, 180, 411, 361))
        self.frame.setStyleSheet("border-color: rgb(0, 85, 255);\n"
"border-left-color: rgb(0, 85, 255);\n"
"border-right-color: rgb(0, 85, 255);\n"
"border-top-color: rgb(0, 85, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.BotonRegistrarse = QtWidgets.QPushButton(self.frame)
        self.BotonRegistrarse.setGeometry(QtCore.QRect(140, 310, 121, 41))
        self.BotonRegistrarse.setObjectName("BotonRegistrarse")
        self.IngresoNombre = QtWidgets.QLineEdit(self.frame)
        self.IngresoNombre.setGeometry(QtCore.QRect(50, 90, 321, 31))
        self.IngresoNombre.setObjectName("IngresoNombre")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 61, 31))
        self.label_3.setObjectName("label_3")
        self.TextoLogin = QtWidgets.QLabel(self.frame)
        self.TextoLogin.setGeometry(QtCore.QRect(160, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TextoLogin.setFont(font)
        self.TextoLogin.setObjectName("TextoLogin")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 120, 61, 31))
        self.label_5.setObjectName("label_5")
        self.IngresoApellido = QtWidgets.QLineEdit(self.frame)
        self.IngresoApellido.setGeometry(QtCore.QRect(50, 150, 321, 31))
        self.IngresoApellido.setObjectName("IngresoApellido")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 180, 61, 31))
        self.label_6.setObjectName("label_6")
        self.RegistroDNI = QtWidgets.QLineEdit(self.frame)
        self.RegistroDNI.setGeometry(QtCore.QRect(50, 210, 321, 31))
        self.RegistroDNI.setObjectName("RegistroDNI")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(50, 240, 71, 31))
        self.label_7.setObjectName("label_7")
        self.RegistroContrasena = QtWidgets.QLineEdit(self.frame)
        self.RegistroContrasena.setGeometry(QtCore.QRect(50, 270, 321, 31))
        self.RegistroContrasena.setObjectName("RegistroContrasena")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TextoIES.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; color:#000000;\">INGRESÁ A TU CUENTA</span></p></body></html>"))
        self.TextoIES.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:20pt; color:#000000;\">I.E.S \'Intendente Hugo Herrera&quot;</span></p></body></html>"))
        self.BotonRegistrarse.setText(_translate("Form", "REGISTRARSE"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Nombre:</span></p></body></html>"))
        self.TextoLogin.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">INGRESÁ A TU CUENTA</span></p></body></html>"))
        self.TextoLogin.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; color:#00007f;\">REGISTRO</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Apellido:</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p>D.N.I:</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p>CONTRASEÑA:</p></body></html>"))
