# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/interfaz_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1359, 703)
        MainWindow.setStyleSheet(" background-color: #1A1D24;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 251, 701))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 701))
        self.widget.setStyleSheet("background-color: #0F2347;\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(0, 220, 261, 45))
        self.pushButton.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../iconos/alumno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 191, 171))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\\../Logo del instituto png.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 260, 251, 45))
        self.pushButton_2.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 300, 251, 45))
        self.pushButton_3.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 340, 251, 45))
        self.pushButton_4.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 380, 251, 45))
        self.pushButton_5.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 420, 251, 45))
        self.pushButton_6.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.bt_volver2 = QtWidgets.QPushButton(self.widget)
        self.bt_volver2.setGeometry(QtCore.QRect(60, 600, 101, 31))
        self.bt_volver2.setStyleSheet("QPushButton{\n"
"     background-color: #1B2330;\n"
"     color: #FFFFFF;\n"
"\n"
"border: 1px solid #2F3A4F;\n"
"border-radius: 12PX;\n"
"\n"
"font-family: \"segoe UI\";\n"
"font-size: 10pt;\n"
"font-weight: 600;\n"
"\n"
"padding: 8px 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"     background-color: #242E3D;\n"
"     border: 1px solid #3B82F6;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background-color: #18202C;\n"
"}")
        self.bt_volver2.setObjectName("bt_volver2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 40, 251, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 18pt;\n"
"    font-weight: 700;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 70, 261, 16))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #B0B0B0;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(530, 170, 75, 21))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(300, 120, 731, 531))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: #1E2433;\n"
"    border: 2px solid #3A4358;\n"
"    border-radius: 15px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(10, 10, 711, 61))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: #18243D;\n"
"    border: 2px solid #2E5CB8;\n"
"    border-radius: 15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 441, 21))
        self.label_5.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(460, 10, 81, 31))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color: #3A4358;\n"
"    color: white;\n"
"    border: 1px solid #4A5568;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4A5568;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(540, 10, 81, 31))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color: #3A4358;\n"
"    color: white;\n"
"    border: 1px solid #4A5568;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4A5568;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(620, 10, 81, 31))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    font: 87 8pt \"Arial Black\";\n"
"\n"
"    background-color: #2E86FF;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 31, 41))
        self.label_8.setStyleSheet("QLabel {\n"
"        border: none;\n"
"}")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("ui\\../iconos/icons8-computadora-de-escritorio-100.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 641, 351))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: #23272F;\n"
"    alternate-background-color: #1D2128;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #323844;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    selection-background-color: #3A4250;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2D3440;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QTableCornerButton::section{\n"
"    background-color: #2D3440;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 66, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(60, 90, 441, 31))
        self.label_6.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 31, 31))
        self.label_7.setStyleSheet("    border: none;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("ui\\../../../../../.designer/iconos/icons8-grupos-de-usuarios-100.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(320, 80, 221, 37))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    min-height: 35px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid #2563EB;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_16.setGeometry(QtCore.QRect(550, 80, 141, 31))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    font: 87 8pt \"Arial Black\";\n"
"    background-color: #2E86FF;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../../../../../.designer/iconos/icons8-signo-más-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon1)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(10, 90, 41, 31))
        self.label_34.setStyleSheet("QLabel {\n"
"       border: none;\n"
"}")
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("ui\\../iconos/icons8-grupos-de-usuarios-100.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.toolButton = QtWidgets.QToolButton(self.frame_2)
        self.toolButton.setGeometry(QtCore.QRect(640, 170, 34, 37))
        self.toolButton.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_2.setGeometry(QtCore.QRect(640, 200, 34, 37))
        self.toolButton_2.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_3.setGeometry(QtCore.QRect(640, 230, 34, 37))
        self.toolButton_3.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_4.setGeometry(QtCore.QRect(640, 260, 34, 37))
        self.toolButton_4.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_5.setGeometry(QtCore.QRect(640, 290, 34, 37))
        self.toolButton_5.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_6.setGeometry(QtCore.QRect(640, 320, 34, 37))
        self.toolButton_6.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_7.setGeometry(QtCore.QRect(640, 350, 34, 37))
        self.toolButton_7.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_8.setGeometry(QtCore.QRect(640, 380, 34, 37))
        self.toolButton_8.setStyleSheet("QToolButton {\n"
"         background-color: transparent;\n"
"         border: none;\n"
"         color: white;\n"
"         font-size: 28px;\n"
"         font-weight: bold;\n"
"}")
        self.toolButton_8.setObjectName("toolButton_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 40, 51, 41))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("ui\\../iconos/gorro-de-graduacion.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.frame_2.raise_()
        self.widget.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_7.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " Tec. Sup. en Desarrollo de Software."))
        self.pushButton_2.setText(_translate("MainWindow", "Tec. en Frutihorticola."))
        self.pushButton_3.setText(_translate("MainWindow", "Tec. en Marketing y Publicidad."))
        self.pushButton_4.setText(_translate("MainWindow", "Profesorado T.I.C"))
        self.pushButton_5.setText(_translate("MainWindow", "Profesorado en Tecnología."))
        self.pushButton_6.setText(_translate("MainWindow", "Profesorado en Fisíca."))
        self.bt_volver2.setText(_translate("MainWindow", "Volver"))
        self.label_2.setText(_translate("MainWindow", "Gestión de Alumnos"))
        self.label_3.setText(_translate("MainWindow", "Administración y seguimiento de estudiantes"))
        self.label_5.setText(_translate("MainWindow", "Tecnicatura Superior en Desarrollo de Software."))
        self.pushButton_13.setText(_translate("MainWindow", "1° Año."))
        self.pushButton_14.setText(_translate("MainWindow", "2° Año."))
        self.pushButton_15.setText(_translate("MainWindow", "3° Año."))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "APELLIDO"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "D.N.I"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CORREO "))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "3725- XXXXXX"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "3725- XXXXXX"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "3624- XXXXXX"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "3624- XXXXXX"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "3624- XXXXXX"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "3624- XXXXXX"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("MainWindow", "3725- XXXXXX"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "00.000.000"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("MainWindow", "3725- XXXXXX"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "-@gmail.com"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "Alumnos - 3° AÑO."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "🔍 Buscar alumno..."))
        self.pushButton_16.setText(_translate("MainWindow", "Agregar Alumno"))
        self.toolButton.setText(_translate("MainWindow", "⋮"))
        self.toolButton_2.setText(_translate("MainWindow", "⋮"))
        self.toolButton_3.setText(_translate("MainWindow", "⋮"))
        self.toolButton_4.setText(_translate("MainWindow", "⋮"))
        self.toolButton_5.setText(_translate("MainWindow", "⋮"))
        self.toolButton_6.setText(_translate("MainWindow", "⋮"))
        self.toolButton_7.setText(_translate("MainWindow", "⋮"))
        self.toolButton_8.setText(_translate("MainWindow", "⋮"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
