# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/interfaz_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1359, 703)
        MainWindow.setStyleSheet(" background-color: #1A1D24;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 251, 701))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 701))
        self.widget.setStyleSheet("background-color: #0F2347;\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(0, 220, 261, 45))
        self.pushButton.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../Documentos/proyecto git hub/proyecto_login/iconos/alumno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 30, 121, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\\../Documentos/proyecto git hub/proyecto_login/Logo del instituto png.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 260, 251, 45))
        self.pushButton_2.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 300, 251, 45))
        self.pushButton_3.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 340, 251, 45))
        self.pushButton_4.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 380, 251, 45))
        self.pushButton_5.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 420, 251, 45))
        self.pushButton_6.setStyleSheet("QWidget{\n"
"    background-color: #1A1D24;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 7pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    border-radius: 8px;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2563EB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #1D4ED8;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #2A3140;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2A3140;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"QWidget{\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"}")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 40, 251, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 18pt;\n"
"    font-weight: 700;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 70, 261, 16))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #B0B0B0;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 40, 47, 41))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("ui\\../Documentos/proyecto git hub/proyecto_login/iconos/gorro-de-graduacion.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1020, 40, 321, 37))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: #222831;\n"
"    color: white;\n"
"    border: 1px solid #2A3140;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    min-height: 35px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid #2563EB;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(280, 130, 351, 351))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: #23272F;\n"
"    alternate-background-color: #1D2128;\n"
"    color: white;\n"
"    border: none;\n"
"    gridline-color: #323844;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    selection-background-color: #3A4250;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: #2D3440;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QTableCornerButton::section{\n"
"    background-color: #2D3440;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(530, 170, 75, 21))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 200, 75, 21))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(530, 230, 75, 21))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(530, 260, 75, 21))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(530, 290, 75, 21))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(530, 320, 75, 21))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #323844;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " Tec. Sup. en Desarrollo de Software."))
        self.pushButton_2.setText(_translate("MainWindow", "Tec. en Frutihorticola."))
        self.pushButton_3.setText(_translate("MainWindow", "Tec. en Marketing y Publicidad."))
        self.pushButton_4.setText(_translate("MainWindow", "Profesorado T.I.C"))
        self.pushButton_5.setText(_translate("MainWindow", "Profesorado en Tecnología."))
        self.pushButton_6.setText(_translate("MainWindow", "Profesorado en Fisíca."))
        self.label_2.setText(_translate("MainWindow", "Gestión de Alumnos"))
        self.label_3.setText(_translate("MainWindow", "Administración y seguimiento de estudiantes"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "🔍 Buscar alumno..."))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "APELLIDO"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "D.N.I"))
