# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/interfaz_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 473)
        self.boton_ingresar = QtWidgets.QPushButton(Form)
        self.boton_ingresar.setGeometry(QtCore.QRect(280, 240, 75, 23))
        self.boton_ingresar.setObjectName("boton_ingresar")
        self.input_dni = QtWidgets.QLineEdit(Form)
        self.input_dni.setGeometry(QtCore.QRect(220, 180, 113, 20))
        self.input_dni.setObjectName("input_dni")
        self.crear_cuentabt = QtWidgets.QPushButton(Form)
        self.crear_cuentabt.setGeometry(QtCore.QRect(170, 240, 75, 23))
        self.crear_cuentabt.setObjectName("crear_cuentabt")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(380, 280, 256, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.boton_ingresar.setText(_translate("Form", "Ingresar"))
        self.crear_cuentabt.setText(_translate("Form", "Crear cuenta"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">guardar en qtdesigner: control + s</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">guardar en vs studioo terminal: pyuic5 ui/interfaz_login.ui -o src/login_ui.py</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ejecutar en vs studio o terminal cmd: python src/main.py</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ejecutar para probar: control + r</p></body></html>"))
