# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/interfaz_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1347, 656)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* INPUTS */\n"
"QLineEdit {\n"
"    background-color: #3c3f41;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4da6ff;\n"
"}\n"
"\n"
"/* BOTONES */\n"
"QPushButton {\n"
"    background-color: #4a4a4a;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* EFECTO HOVER */\n"
"QPushButton:hover {\n"
"    background-color: #5c5c5c;\n"
"}\n"
"\n"
"/* CUANDO SE APRIETA */\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 541, 661))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\\../../../Desktop/Diseño sin título.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(700, 190, 411, 361))
        self.frame.setStyleSheet("border-color: rgb(0, 85, 255);\n"
"border-left-color: rgb(0, 85, 255);\n"
"border-right-color: rgb(0, 85, 255);\n"
"border-top-color: rgb(0, 85, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.QPttoushBun = QtWidgets.QPushButton(self.frame)
        self.QPttoushBun.setGeometry(QtCore.QRect(150, 280, 121, 41))
        self.QPttoushBun.setObjectName("QPttoushBun")
        self.IngresoDNI = QtWidgets.QLineEdit(self.frame)
        self.IngresoDNI.setGeometry(QtCore.QRect(50, 180, 321, 51))
        self.IngresoDNI.setObjectName("IngresoDNI")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 61, 31))
        self.label_3.setObjectName("label_3")
        self.TextoLogin = QtWidgets.QLabel(self.frame)
        self.TextoLogin.setGeometry(QtCore.QRect(60, 50, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.TextoLogin.setFont(font)
        self.TextoLogin.setObjectName("TextoLogin")
        self.BotonCrearCuenta = QtWidgets.QPushButton(Form)
        self.BotonCrearCuenta.setGeometry(QtCore.QRect(860, 560, 91, 31))
        self.BotonCrearCuenta.setObjectName("BotonCrearCuenta")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(800, 0, 161, 181))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("ui\\../../../Desktop/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.TextoIES = QtWidgets.QLabel(Form)
        self.TextoIES.setGeometry(QtCore.QRect(110, 50, 361, 111))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.TextoIES.setFont(font)
        self.TextoIES.setStyleSheet("background-color: transparent;")
        self.TextoIES.setObjectName("TextoIES")
        self.frame.raise_()
        self.label.raise_()
        self.BotonCrearCuenta.raise_()
        self.label_4.raise_()
        self.TextoIES.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.QPttoushBun.setText(_translate("Form", "INGRESAR"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">D.N.I:</span></p></body></html>"))
        self.TextoLogin.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">INGRESÁ A TU CUENTA</span></p></body></html>"))
        self.TextoLogin.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:26pt; color:#00007f;\">INGRESÁ A TU CUENTA</span></p></body></html>"))
        self.BotonCrearCuenta.setText(_translate("Form", "CREAR CUENTA"))
        self.TextoIES.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; color:#000000;\">INGRESÁ A TU CUENTA</span></p></body></html>"))
        self.TextoIES.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:20pt; color:#000000;\">I.E.S \'Intendente Hugo Herrera&quot;</span></p></body></html>"))
