# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Documentos\proyecto git hub\proyecto_login\ui\interfaz_registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 715)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* INPUTS */\n"
"QLineEdit {\n"
"    background-color: #3c3f41;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4da6ff;\n"
"}\n"
"\n"
"/* BOTONES */\n"
"QPushButton {\n"
"    background-color: #4a4a4a;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* EFECTO HOVER */\n"
"QPushButton:hover {\n"
"    background-color: #5c5c5c;\n"
"}\n"
"\n"
"/* CUANDO SE APRIETA */\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(740, 80, 411, 571))
        self.frame.setStyleSheet("border-color: rgb(0, 85, 255);\n"
"border-left-color: rgb(0, 85, 255);\n"
"border-right-color: rgb(0, 85, 255);\n"
"border-top-color: rgb(0, 85, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.BotonGuardar = QtWidgets.QPushButton(self.frame)
        self.BotonGuardar.setGeometry(QtCore.QRect(150, 470, 121, 41))
        self.BotonGuardar.setStyleSheet("QPushButton {\n"
"    background-color: #1B5E20;   /* Verde oscuro */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4CAF50;   /* Verde claro al pasar el mouse */\n"
"}\n"
"QPushButton {\n"
"    background-color: #1B5E20;\n"
"    color: white;\n"
"    border: 2px solid #2E7D32;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"    border: 2px solid #A5D6A7;\n"
"}")
        self.BotonGuardar.setObjectName("BotonGuardar")
        self.IngresoNombre = QtWidgets.QLineEdit(self.frame)
        self.IngresoNombre.setGeometry(QtCore.QRect(50, 140, 321, 31))
        self.IngresoNombre.setObjectName("IngresoNombre")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.TextoLogin = QtWidgets.QLabel(self.frame)
        self.TextoLogin.setGeometry(QtCore.QRect(140, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.TextoLogin.setFont(font)
        self.TextoLogin.setObjectName("TextoLogin")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.IngresoApellido = QtWidgets.QLineEdit(self.frame)
        self.IngresoApellido.setGeometry(QtCore.QRect(50, 230, 321, 31))
        self.IngresoApellido.setObjectName("IngresoApellido")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(60, 280, 61, 31))
        self.label_6.setObjectName("label_6")
        self.RegistroDNI = QtWidgets.QLineEdit(self.frame)
        self.RegistroDNI.setGeometry(QtCore.QRect(50, 310, 321, 31))
        self.RegistroDNI.setObjectName("RegistroDNI")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(60, 360, 91, 31))
        self.label_7.setObjectName("label_7")
        self.RegistroContrasena = QtWidgets.QLineEdit(self.frame)
        self.RegistroContrasena.setGeometry(QtCore.QRect(50, 390, 321, 31))
        self.RegistroContrasena.setObjectName("RegistroContrasena")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 531, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\User\\OneDrive\\Documentos\\proyecto git hub\\proyecto_login\\ui\\../kkk.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BotonGuardar.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" color:#55ff00;\">Guardar</span></p></body></html>"))
        self.BotonGuardar.setText(_translate("Form", "Guardar"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Nombre:</span></p></body></html>"))
        self.TextoLogin.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#00007f;\">INGRESÁ A TU CUENTA</span></p></body></html>"))
        self.TextoLogin.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">REGISTRO</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Apellido:</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p>D.N.I:</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p>Contraseña:</p></body></html>"))
